package eventradatabase

import (
	"context"
	"database/sql"
	"fmt"

	"database/internal/domain/admin"
	_ "github.com/go-sql-driver/mysql"
)

// Repository is the MySQL-backed implementation of admin.Repository.
type Repository struct {
	db *sql.DB
}

func New(db *sql.DB) *Repository {
	return &Repository{db: db}
}

// Create inserts a new admin row into the usuario table.
// The ID is generated by MySQL via AUTO_INCREMENT.
func (r *Repository) Create(ctx context.Context, a admin.Admin) (admin.Admin, error) {
	res, err := r.db.ExecContext(
		ctx,
		`INSERT INTO user (name, last_name, email, password, type)
		 VALUES (?, ?, ?, ?, 'admin')`,
		a.Name,
		a.LastName,
		a.Email,
		a.Password,
	)
	if err != nil {
		return admin.Admin{}, fmt.Errorf("insert user: %w", err)
	}

	lastID, err := res.LastInsertId()
	if err != nil {
		return admin.Admin{}, fmt.Errorf("last insert id: %w", err)
	}

	var result admin.Admin
	err = r.db.QueryRowContext(
		ctx,
		`SELECT id, name, last_name, email FROM user WHERE id = ?`,
		lastID,
	).Scan(&result.ID, &result.Name, &result.LastName, &result.Email)
	if err != nil {
		return admin.Admin{}, fmt.Errorf("select user by id: %w", err)
	}

	return result, nil
}
