package eventradatabase

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"database/internal/domain/admin"
	_ "github.com/go-sql-driver/mysql"
)

// Repository is the MySQL-backed implementation of admin.Repository.
type Repository struct {
	db *sql.DB
}

func New(db *sql.DB) *Repository {
	return &Repository{db: db}
}

// Create inserts a new admin row into the admins table.
// The ID is generated by the repository layer using the schema convention
// "admin_<unix_ms>" so the caller never needs to supply it.
func (r *Repository) Create(ctx context.Context, a admin.Admin) (admin.Admin, error) {
	id := fmt.Sprintf("admin_%d", time.Now().UnixMilli())
	createdAt := time.Now().UnixMilli()

	_, err := r.db.ExecContext(
		ctx,
		`INSERT INTO admins
			(id, username, email, password_hash, name, last_name, created_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		id,
		id,        // username: igual al id por ahora
		"",        // email
		"",        // password_hash
		a.Name,
		a.LastName,
		createdAt,
	)
	if err != nil {
		return admin.Admin{}, fmt.Errorf("insert admin: %w", err)
	}

	// Leer la fila persistida y mapearla al dominio.
	var result admin.Admin
	err = r.db.QueryRowContext(
		ctx,
		`SELECT id, name, last_name FROM admins WHERE id = ?`,
		id,
	).Scan(&result.ID, &result.Name, &result.LastName)
	if err != nil {
		return admin.Admin{}, fmt.Errorf("select admin by id: %w", err)
	}

	return result, nil
}
